# Generated by Django 6.1.1 on 2026-09-23 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('COMPRA', 'Compra a proveedor'), ('RECETA', 'Consumo por receta'), ('AJUSTE', 'Ajuste manual')], max_length=20)),
                ('accion', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('g', 'Gramo'), ('ml', 'Mililitro'), ('kg', 'Kilogramo'), ('l', 'Litro'), ('cajas', 'Cajas'), ('u', 'Unidad')], max_length=20)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo')),
            ],
        ),
    ]
