# Generated by Django 6.1.1 on 2026-09-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_reserva', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_personas', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_reserva', models.CharField(choices=[('Mesa', 'Mesa'), ('Para llevar', 'Para llevar')], default='Para llevar', max_length=50)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('asistencia', models.CharField(blank=True, choices=[('Asistió', 'Asistió'), ('No asistió', 'No asistió')], max_length=20, null=True)),
            ],
        ),
    ]
