# Generated by Django 6.1.1 on 2026-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='postre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
